### ISSUE TITLE
Error on 'chrome.types' when starting extension

### ISSUE THREAD

**Issue by DinisCruz** [mihaip/chrome-app-repl#1]
When it starts I got this error
![image](https://cloud.githubusercontent.com/assets/656739/5126568/dd3659ee-70c5-11e4-927f-644ce6a14b52.png)

For reference the 'get goggle' demo that is provided on the README.md file works ok 
![image](https://cloud.githubusercontent.com/assets/656739/5126638/6566457c-70c6-11e4-8b22-2b9ea7a83614.png)

**Comment by mihaip** [comment]
What version of Chrome are you seeing this with? Dev channel (40.0.2214.10) and Canary (41.0.2225.0) are fine for me.

**Comment by mihaip** [comment]
Obsolete given https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html
